In [1]:
# Infoscience v library science; m e t a d a t a for libraries
# Beskrivelsen av produksjonslinjen og fremgangsmåten.
# Linked data-modell av det som er gjort; søkbar i SPARQL??? WUT
# 6 Tematikker, 2-3 sider per
# Innhøsting-berikelse-erfaring-formidling
# Formidling av arbeid; HVORFOR og HVORDAN, ikke bare HVA.

# HEIIII vent litt nå. Skal vi ikke heller søke på kommune og deretter hente ut alle postnummere for kommunen for
# å søke i dem? -- Ja, det gjør vi nå.

# PIP rett i Conda-cmd

# Postens data -> SSB, NSD. NSD -> NSD.

# Celle 8:
# Nå har vi problemer. HiO, HiOA og OsloMet er listet enda. Vi må gjøre følgende:
# 1: Få dette her i en liste
# 2: Luke ut duplikater basert på sammenslått navn
# 2 kan oppnås ved å søke med variabel Sammenslått navn i navnefeltet til tabell 123, eller hva?
# !! Noen har sammenslått navn: None
# Kan vi flytte søk til API-siden kanskje?
# if sammenslått navn is not None:
# where sammenslått navn = navn
# ta disse

# ... Flere problemer. 
# USN er ikke synlig om man søker på Drammen, men de har studiested der. Ehhhmmm..
# Hva er "buskerud fylkeskommune" i denne konteksten?

In [2]:
import pandas as pd
import json
import requests
import io

In [3]:
# "Brukergrensesnitt"
# Kommunen man er interessert i; husk å gjøre stor forbokstav dersom user input
kommuneNavn = 'drammen'
# Årstall for statistikk; sjekk om NSD tilbyr statistikk pr år
aarTilSSB = '2020'

In [4]:
# Variabeldeklarasjon; ikke rør
# INTEGER!! Må gjøres om til string før SSB-søk. I tillegg! str.len og ledende nuller før SSB-søk.
postnummer = 452
kommuneID = 1
prefiksSSB = 'K-'
postnumre = []

In [5]:
print("Forsøker å hente tabell 211 fra NSD...")
# JSON-data fra NSD tabell 211: register med kontaktinformasjon
# Dette er da register over "metadata" fra høgskoler og universitet. Det er egentlig ikke så mye informasjon vi skal ha
# -> Vi skal sammenligne XX i NSDs data samt hente postnummer og legge i variabel.
with open('resources/nsd211.json', encoding='utf-8') as json_file:
    nsddata = json.load(json_file)
# json_dumps prøver å stappe inn ASCII-karakterer ("amerikanisering"). Må ha ensure_ascii=False for æøå.
# print(json.dumps(nsddata, indent = 4, ensure_ascii=False))

# Variabelen postnummer hentes fra NSD. Dette fasiliterer oversettelse til kommunenavn.
# postnummer = postnummer
if len(nsddata) >= 1:
    print("OK. Hentet", len(nsddata), "innførsler fra NSD.")
else:
    print("Fikk ikke hentet tabell 211.")
    quit()

Forsøker å hente tabell 211 fra NSD...
OK. Hentet 276 innførsler fra NSD.

In [6]:
print("Søker i Postens kommune- og postnummerregister...")
df2 = pd.read_csv("resources/postnummerregister.csv", sep=',')
# df2 kommer med stor bokstav foran. Jeg vil helst at det er smått gjennom hele.
df2.columns = ['postnummer','poststed','kommunenummer','kommunenavn','kategori']
# Anvend zfill for å få tilbake ledende nuller i post- og kommunenummer.
df2['postnummer'] = df2['postnummer'].astype(str).str.zfill(4)
df2['kommunenummer'] = df2['kommunenummer'].astype(str).str.zfill(4)

kommuner = []
for kommune in df2['kommunenavn'].unique():
    if kommune not in kommuner:
        kommuner.append(kommune)

if kommuneNavn.upper() in kommuner:
    # Vi søker opp samtlige postnummer i Postens register.
    kommunensPostnummer = df2[df2['kommunenavn'] == kommuneNavn.upper()][['postnummer','kommunenummer']]
    # Vi setter var kommuneID fra samme søk. Kommunenummer skal uansett bare være én verdi hele veien ned.
    kommuneID = kommunensPostnummer['kommunenummer'].values[0]
    # Postnummer settes som et tilfeldig postnummer. Vi bruker ikke denne varaiabelen videre.
    postnummer = kommunensPostnummer['postnummer'].values[0]
    print("OK. Målkommune låst:", kommuneNavn.upper())
else:
    print("Kritisk feil: Er du sikker på at det er en kommune? Har du skrevet navnet _helt_ riktig..?")
    quit()
#print(postnumre)
#kommunensPostnummer

Søker i Postens kommune- og postnummerregister...
OK. Målkommune låst: DRAMMEN

In [7]:
print("Henter alle postnummer fra kommune", kommuneID, kommuneNavn.capitalize() +"...")
if not postnumre:
    print("Oppretter ny liste...")
else:
    print("Tømmer eksisterende liste...")
    postnumre = []
print("Befolker liste...")
# Her henter vi en liste over unike postnummer som skal anvendes for å søke i NSD.
for postnum in kommunensPostnummer['postnummer'].unique():
    if postnum not in postnumre:
        postnumre.append(postnum)
if not postnumre:
    print("Listebefolkning feilet. Kommunen har kanskje ingen postnummer...?")
else:
    print("OK. Hentet", len(postnumre), "unike postnummer fra målkommune.")

Henter alle postnummer fra kommune 3005 Drammen...
Oppretter ny liste...
Befolker liste...
OK. Hentet 62 unike postnummer fra målkommune.

In [15]:
print("Henter institusjoner fra NSD... \n")
# Vi bruker listen postnumre for å søke i NSD. Da henter vi inn ALLE skoler med postnummer listet i denne kommunen.
i = -1
for element in nsddata:
    i = i + 1
    for kode in postnumre:
        if element.get("Postnummer") == kode:
            print("Innførsel", i)
            print("Navn:", element.get("Institusjonsnavn"))
            print("Postnummer:", element.get("Postnummer"))
            print("Sammenslått navn:", element.get("Sammenslått navn"))
            print('\n')
print("Institusjoner innhentet.")

Henter institusjoner fra NSD...

Innførsel 105
Navn: Drammen sykepleierhøgskole
Postnummer: 3019
Sammenslått navn: Drammen sykepleierhøgskole


Innførsel 214
Navn: Buskerud fylkeskommune
Postnummer: 3007
Sammenslått navn: Buskerud fylkeskommune


Institusjoner innhentet.

In [9]:
nsddata[214]

{'Institusjonskode': '9006',
 'Institusjonsnavn': 'Buskerud fylkeskommune',
 'Adresse': 'Postboks 3563, 3007 DRAMMEN',
 'Postnummer': '3007',
 'Gyldig fra': '11111',
 'Gyldig til': '99999',
 'Telefon': '32808500',
 'Telefax': None,
 'Institusjonstypekode': '90',
 'Typenavn': 'Fylkeskommuner',
 'Kortnavn': None,
 'Departementid': None,
 'Dep_navn': None,
 'Institusjonskode (sammenslått)': '9006',
 'Sammenslått navn': 'Buskerud fylkeskommune'}

In [11]:
print("Henter kommunedata fra SSB...")
# SSB
# SSBs CSV er ikke UTF-8 (sier dokumentasjonen), så vi angir parameter encoding ISO-8859-1..?
# Gjør kommuneID til str, ikke int.
kommuneTilSSB = prefiksSSB + str(kommuneID)
data = {
  "query": [
    {
      "code": "Region",
      "selection": {
        "filter": "agg:KommSummer",
        "values": [
          kommuneTilSSB,
        ]
      }
    },
    {
      "code": "Kjonn",
      "selection": {
        "filter": "item",
        "values": [
          "1",
          "2"
        ]
      }
    },
    {
      "code": "Alder",
      "selection": {
        "filter": "agg:TiAarigGruppering",
        "values": [
          "F00-09",
          "F10-19",
          "F20-29",
          "F30-39",
          "F40-49",
          "F50-59",
          "F60-69",
          "F70-79",
          "F80-89",
          "F90-99",
          "F100G10+"
        ]
      }
    },
    {
      "code": "Tid",
      "selection": {
        "filter": "item",
        "values": [
          aarTilSSB
        ]
      }
    }
  ],
  "response": {
    "format": "csv2"
  }
}
response = requests.post("https://data.ssb.no/api/v0/no/table/07459/", json=data)
if response.status_code == 200:
    print("OK. Responskode 200 - tabell hentet.")
elif response.status_code == 201:
    print("Responskode 201 - Created? .. Ja, det kan jo hende.")
else:
    print("Responskode", response.status_code +". Noe er feil, ellers er serveren nede.")
# Assign responsen til en variabel, deretter anvend io for å konvertere til pandas dataframe.
# Hvorfor variabel? Eeee. Kan være fint?
ssbdata = response.text
df = pd.read_csv(io.StringIO(ssbdata))

Henter kommunedata fra SSB...
OK. Responskode 200 - tabell hentet.

In [12]:
# df

In [13]:
print("Renser data...")
# Her var det mye tjafs. Bokstaver og koder og greier.
# Jeg vil gjerne at df får litt mer lesevennlige kolonnenavn.
df.columns = ['region','kjønn','alder','år','type','antall']
# Fjern de første 2 tegn fra Kjønn, og de første 5 tegn fra Alder. Derfor:
# Utryddelse av uønskede karakterer fra SSBs data via Regex
df['region'] = df['region'].str[7:]
# df['region'].replace('\d\d\d\d ','', inplace=True, regex=True)
# df['region'].replace(r'\(.*\)','', inplace=True, regex=True)
df['kjønn'].replace('\d ','', inplace=True, regex=True)
df['alder'].replace(r"[a-zA-Z]",'', inplace=True, regex=True)
df['alder'].replace(u"\xe5",'', inplace=True, regex=True)
df

Renser data...

     region    kjønn   alder    år      type  antall
0   Drammen     Menn    0-9   2020  Personer    5689
1   Drammen     Menn  10-19   2020  Personer    6415
2   Drammen     Menn  20-29   2020  Personer    6390
3   Drammen     Menn  30-39   2020  Personer    7169
4   Drammen     Menn  40-49   2020  Personer    7352
5   Drammen     Menn  50-59   2020  Personer    6894
6   Drammen     Menn  60-69   2020  Personer    5048
7   Drammen     Menn  70-79   2020  Personer    3922
8   Drammen     Menn  80-89   2020  Personer    1449
9   Drammen     Menn  90-99   2020  Personer     233
10  Drammen     Menn  100     2020  Personer       3
11  Drammen  Kvinner    0-9   2020  Personer    5448
12  Drammen  Kvinner  10-19   2020  Personer    6007
13  Drammen  Kvinner  20-29   2020  Personer    6118
14  Drammen  Kvinner  30-39   2020  Personer    6788
15  Drammen  Kvinner  40-49   2020  Personer    7207
16  Drammen  Kvinner  50-59   2020  Personer    6507
17  Drammen  Kvinner  60-69   2020  Personer    5466
18  Drammen  Kvinner  70-79   2020  Personer    4622
19  Drammen  Kvinner  80-89   2020  Personer    2097
20  Drammen  Kvinner  90-99   2020  Personer     550
21  Drammen  Kvinner  100     2020  Personer      12

In [14]:
# OVERFLØDIG; UTFØRES PÅ API-NIVÅ
# Konstruer ny df for å holde navn på variabelen som holder Kommunenavn fra df2: anvend variabelen for å søke i Region
# newdf = df[df.region.str.contains("Drammen")]
# newdf[newdf['år'] == 2018].head(40)